### ISSUE TITLE
监控一段时间报错问题.

### ISSUE THREAD

**Issue by DevinYul** [wanwujiedao/spring-boot-starter-canal#6]
运行一段时间就会出现以下错误,请大佬给结束下
2019-05-24 12:51:55.630 ERROR 80373 --- [pool-1-thread-1] c.s.c.c.a.AbstractMessageTransponder     : pool-1-thread-1: 发生错误!! 

com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:296) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:269) ~[canal.client-1.0.25.jar:na]
	at com.starter.canal.client.abstracts.AbstractMessageTransponder.run(AbstractMessageTransponder.java:112) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_161]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_161]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_161]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_161]
	at java.nio.channels.Channels.writeFully(Channels.java:98) ~[na:1.8.0_161]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_161]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_161]
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458) ~[na:1.8.0_161]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:381) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:369) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:281) ~[canal.client-1.0.25.jar:na]
	... 7 common frames omitted

**Comment by DevinYul** [comment]
有人给解答一下吗

**Comment by ab8846254** [comment]
请问你这个是跑了多久？另外是因为insert千万级数据的时候报的错吗？
